questions/urls.py
from django.urls import path
from .views import *

app_name='Question'
urlpatterns=[
    path("v1/questions",QuestionView.as_view()),
    path("v1/questions/<str:pk>",QuestionView.as_view()),
    path("v1/answers",AnswerView.as_view()),
    path("v1/answers/<str:pk>",AnswerView.as_view()),
]
  

quizproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizzes.urls', namespace ='quizzes')),
    path('test/',include('questions.urls', namespace ='questions'))

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizzes/urls.py
from django.urls import path



from .views import (QuizListView, quiz_view, quiz_data_view,save_quiz_view, getapi)

app_name= 'quizzes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/',quiz_data_view , name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
        # path('getapi/', getapi, name='getapi'),

]

questions/models.py
from django.db import models
from quizzes.models import Quiz

class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
  

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
   

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizzes/models.py
from django.db import models
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizzes'

results/models.py
from django.db import models
from quizzes.models import Quiz
from django.contrib.auth.models import User

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

questions/views.py
from django.shortcuts import render
# from django.utils.decorators import method_decorator
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Question,Answer
from .serializers import QuestionSerializer,AnswerSerializer
# from decorator.auth_decorator import token_decode

class QuestionView(APIView):
    
    # permission_classes = (IsAuthenticated,)
    # @method_decorator(token_decode())
    def post(self,request,user_id):
        data = request.data 
        data['user_id'] = user_id
        questions_list=Question(data=data)
        questions_list.is_valid(raise_exception=True)

        questions_list.save()
        return Response(data=questions_list.data,status=status.HTTP_200_OK)

    def get_question(self, pk):
        try:
            return Question.objects.get(pk=pk)
        except Question.DoesNotExist:
            raise status.HTTP_404_NOT_FOUND


    def get(self,request,pk=None,format=None):
        if pk==None:
            question_list=Question.objects.all()
            stat=True
        else:
            stat=False
            question_list=self.get_question(pk)
        serialized_question=QuestionSerializer(question_list,many=stat)
        return Response(data=serialized_question.data,status=status.HTTP_200_OK)
        

class AnswerView(APIView):
    
    # permission_classes = (IsAuthenticated,)
    # @method_decorator(token_decode())
    def post(self,request,user_id):
        data = request.data 
        data['user_id'] = user_id
        answers_list=Answer(data=data)
        answers_list.is_valid(raise_exception=True)

        answers_list.save()
        return Response(data=answers_list.data,status=status.HTTP_200_OK)

    def get_answer(self, pk):
        try:
            return Answer.objects.get(pk=pk)
        except Answer.DoesNotExist:
            raise status.HTTP_404_NOT_FOUND


    def get(self,request,pk=None,format=None):
        if pk==None:
            answers_list=Answer.objects.all()
            stat=True
        else:
            stat=False
            answers_list=self.get_answer(pk)
        serialized_answer=AnswerSerializer(answers_list,many=stat)
        return Response(data=serialized_answer.data,status=status.HTTP_200_OK)
        

quizzes/views.py
from django.shortcuts import render
from .models import Quiz
from django.http import JsonResponse
from django.views.generic.list import ListView
from questions.models import Question, Answer
from results.models import Result
import requests
from django.http.response import JsonResponse
from django.db import models, transaction

@transaction.atomic
def getapi(request):
    response= requests.get('https://opentdb.com/api.php?amount=50&category=17&difficulty=medium&type=multiple')
    for ques in response.json()['results']:
        question = Question.objects.create(text= ques['question'],quiz_id = '6')
        Answer.objects.create(text=ques['correct_answer'],correct=1,question_id=question.id)
        for ans in ques['incorrect_answers']:
            Answer.objects.create(text=ans,correct=0,question_id=question.id)
    return JsonResponse({"message": "sucessfully imported"})

# Create your views here.
class QuizListView(ListView):
    model = Quiz
    template_name = 'quizzes/main.html'

def quiz_view(request, pk):
    quiz =Quiz.objects.get(pk=pk)
    return render(request, 'quizzes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

results/views.py
from django.shortcuts import render

# Create your views here.

quizzes/templates/quizzes/main.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
     <script src = "{% static 'main.js' %}" defer>
</script>
{% endblock scripts %}



{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id ='modal-body-confirm'>
<!--     things to pass from js using getE  lement by Id, which is super lit-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
        <button type="button" id ='start-button' class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>



<div style='text-align:center' class ='h1'>Quiz List </div>
<hr>
{% for obj in object_list %}
<!--since this is a class based view, object_list will
access the attributes of the model mentioned in the class-->
<button
class ='btn btn-link modal-button'
data-pk ="{{obj.pk}}"
data-quiz = "{{obj.name}}"
data-questions = "{{obj.number_of_questions}}"
data-difficulty     = "{{obj.difficulty}}"
data-time = "{{obj.time}}"
data-pass  = "{{obj.required_score_to_pass}}"

 data-toggle="modal"
data-target="#quizModal">

    <style>

.flex-container > div {


text-align: center;
border: 7px solid green;
border-radius: 20px;
width: 300px;
height: 200px;
padding-top: 100px;
margin-left: 400px;


}
.edit{
  display:inline-block;
  width:25%;
font-size: 200%;
padding-top: 40px;
}
</style>



<div class="flex-container">
  <div class="edit">{{obj.name}}</div>


</div>



</button>
 <br>
{% endfor %}
{% endblock content %}

quizzes/templates/quizzes/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
     <script src = "{% static 'quiz.js' %}" defer>

</script>

{% endblock scripts %}



{% block title %}
You are in
{{obj.name}} page.
{% endblock title %}


{% block content %}

     <p style="text-align:center;color:blue;font-weight:bold;font-size:1.4rem;">You are in <span style="color:crimson;font-weight:bold;font-size:1.4rem;" >{{obj.name}}   </span>
page.</p>
<p style="text-align:center;color:purple;font-weight:bold;font-size:1.4rem;">Required score to pass<span style="color:green">
"{{obj.required_score_to_pass}}"!</span></p>
<div style="text-align:center;color:blue;font-weight:bold;font-size:1.4rem;" id="timer-box"></div>
<div style="text-align:right;">
<a href="{% url 'quizzes:main-view' %}" style="text-align:center;" class="btn btn-danger">Go back</a>
     </div>
<hr>

<form id ='quiz-form' class ='mt-3 mb-3'>
     {% csrf_token %}
<div id ='quiz-box'></div>
     <button type = 'submit' class = 'btn btn-primary mt-3'>Save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
<!--    <link rel="stylesheet" href={% static 'style.css' %}>-->

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>